export const USER_PENDING = 'USER_PENDING';

export const ADD_USER = 'ADD_USER';
export const ADD_USER_FAILED = 'ADD_USER_FAILED';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_PENDING = 'ADD_USER_PENDING';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';