export const CHANGE_AUTH = 'CHANGE_AUTH';
export const CHECK_AUTHENTICATION = 'CHECK_AUTHENTICATION';
export const ADD_USER = 'ADD_USER';
export const ADD_USER_FAILED = 'ADD_USER_FAILED';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_PENDING = 'ADD_USER_PENDING';