export default {
	projects: [
		{
			name: 'Galvanize Staff',
			repo: 'https://github.com/namkai/Galvanize_Staff',
			website: 'https://sf-galvanize-staff.herokuapp.com/',
			description: 'Built a site for Galvanize that shows all their staff members',
			technologies: 'HTML, CSS, Javascript, React, Redux, Reselect, Materialize',
			photo: 'https://pbs.twimg.com/profile_images/595327206638755840/x9_fTdew_400x400.jpg',
			timeStamp: '1494988479027',
		},
		{
			name: 'API Explorer',
			repo: 'https://github.com/namkai/API_Explorer',
			website: '',
			description: 'Similar to Postman or Swagger.ui',
			technologies: 'HTML, CSS, Javascript, React, Redux, Redux-Saga, Axios, Materialize',
			photo: 'http://cdn.klynt.net/wp-content/uploads/2014/10/API-e1414438807662.jpg',
			timeStamp: '1494799139889',
		},
		{
			name: 'Reddit Clone',
			repo: 'https://github.com/namkai/Reddit_Clone',
			website: 'http://reddit.com/r/all',
			description: 'Front-End for Reddit',
			technologies: 'HTML, CSS, Javascript, React, Redux, Redux-Saga, Axios, Materialize',
			photo: 'https://www.thewrap.com/wp-content/uploads/2015/02/reddit-logo.jpg',
			timeStamp: '1494988394978',
		},
		{
			name: 'Chess AI',
			repo: 'https://github.com/namkai/Chess_AI',
			website: 'http://simple-chess-ai.herokuapp.com/',
			description: 'Using minimax algorithm, alpha beta pruning, and heuristics we were able to produce an AI that move’s intelligently.',
			technologies: 'HTML, CSS, Javascript',
			photo: 'https://images.fineartamerica.com/images/artworkimages/mediumlarge/1/chess-pieces-debbie-dewitt.jpg',
			timeStamp: '1494988394978',
		},
	],
	deleted: [],
};
